### ISSUE TITLE
Twiiter (now X) has changed the way that Ads are rendered.

### ISSUE THREAD

**Issue by gmonahan** [wwerner/promute#5]
They no longer have the "Promoted" footer, but now show an "Ad" near the menu.

**Comment by wwerner** [comment]
I've been trying to reproduce/update this, but, for some reasons, I'm not getting any promoted content at this time. 
I reset all muted accounts and updated my ad settings, perhaps something will show up eventually. I'll keep you posted.

**Comment by wwerner** [comment]
Ok, got it.
It seems Brave does a really decent job blocking twitter ads now, at least they only started to show up once I turned it off.

Anyway, a patched version is coming.

**Comment by wwerner** [comment]
I've published v1.0.8 to the FF & Chrome webstore. Both versions are currently being reviewed and should be available shortly.

Thanks @gmonahan for bringing it to my attention.
